version: "3"
services:
  dump1090-fa:
    image: imple/dump1090-fa
    ports:
      - "8080:8080"
    privileged: True
  flightaware:
    image: imple/flightaware
    env_file: flightaware.env
    links:
      - dump1090-fa:dump1090
