version: "3"
services:
  dump1090-fa:
    image: imple/dump1090-fa
    ports:
      - "8080:8080"
      - "30003:30003"
      - "30005:30005"
      - "30104:30104"
    privileged: True
  flightaware:
    image: imple/flightaware
    links:
      - dump1090-fa:dump1090
