version: "3"
services:
  dump1090-fa:
    image: imple/dump1090-fa
    ports:
      - "8080:8080"
    privileged: True
    restart: unless-stopped
  flightaware:
    image: imple/flightaware
    env_file: flightaware.env
    links:
      - dump1090-fa:dump1090
    depends_on:
      - dump1090-fa
    restart: unless-stopped
  flightradar24:
    image: imple/flightradar24
    env_file: flightradar24.env
    links:
      - dump1090-fa:dump1090
    depends_on:
      - dump1090-fa
    restart: unless-stopped
